<?php

namespace Proxies;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class PHPTourConferencierProxy extends \PHPTour\Conferencier implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $documentPersister;
    private $identifier;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->documentPersister = $documentPersister;
        $this->identifier = $identifier;
    }
    private function __load()
    {
        if (!$this->__isInitialized__ && $this->documentPersister) {
            $this->__isInitialized__ = true;
            if ($this->documentPersister->load($this->identifier, $this) === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->identifier);
            }
            unset($this->documentPersister, $this->identifier);
        }
    }

    
    public function setEntreprise($entreprise)
    {
        $this->__load();
        return parent::setEntreprise($entreprise);
    }

    public function getEntreprise()
    {
        $this->__load();
        return parent::getEntreprise();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }


    public function __sleep()
    {
        return array('id', 'nom', 'prenom', 'entreprise');
    }
}