<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class PHPTourConferencierHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data)
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nom'])) {
            $value = $data['nom'];
            $return = (string) $value;
            $this->class->reflFields['nom']->setValue($document, $return);
            $hydratedData['nom'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['prenom'])) {
            $value = $data['prenom'];
            $return = (string) $value;
            $this->class->reflFields['prenom']->setValue($document, $return);
            $hydratedData['prenom'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['entreprise'])) {
            $value = $data['entreprise'];
            $return = (string) $value;
            $this->class->reflFields['entreprise']->setValue($document, $return);
            $hydratedData['entreprise'] = $return;
        }
        return $hydratedData;
    }
}