<?php

namespace Proxies;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class PHPTourSlidesProxy extends \PHPTour\Slides implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $documentPersister;
    private $identifier;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->documentPersister = $documentPersister;
        $this->identifier = $identifier;
    }
    private function __load()
    {
        if (!$this->__isInitialized__ && $this->documentPersister) {
            $this->__isInitialized__ = true;
            if ($this->documentPersister->load($this->identifier, $this) === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->identifier);
            }
            unset($this->documentPersister, $this->identifier);
        }
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getFichier()
    {
        $this->__load();
        return parent::getFichier();
    }

    public function setFichier($fichier)
    {
        $this->__load();
        return parent::setFichier($fichier);
    }

    public function getFileName()
    {
        $this->__load();
        return parent::getFileName();
    }

    public function getLength()
    {
        $this->__load();
        return parent::getLength();
    }


    public function __sleep()
    {
        return array('_id', '_fichier', 'uploadDate', 'length', 'filename', 'md5');
    }
}